# Copyright 2023 Alphia GmbH
name: orare
description: 'Discover your healthy power of gratitude. Write daily and share joy.'
publish_to: 'none'
version: 2.3.2+42
# News: Weâ€™re always crafting new features and squishing bugs. Keep your app updated for a refreshing experience.

environment:
  sdk: ^3.8.1

dependencies:
  alphia_core:
    git:
      url: https://github.com/alphia-gmbh/flutter-package-core.git
      # path: alphia_core
      ref: main
  archive: ^4.0.1
  async: ^2.11.0
  cloud_firestore: ^6.0.2
  cloud_functions: ^6.0.2
  firebase_app_check: ^0.4.1
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.0.1
  flutter_local_notifications: ^19.0.0
  flutter_secure_storage: ^10.0.0
  intl: any
  in_app_review: ^2.0.9
  material_symbols_icons: ^4.2801.0
  path_provider: ^2.1.0
  screenshot: ^3.0.0
  share_plus: ^12.0.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
      # font-inter-regular.ttf
  fonts:
    - family: Roboto # Necessary for web version to avoid online request of Roboto as fallback font
      fonts:
        - asset: assets/font-inter-regular.ttf
